#!/usr/bin/python2

import sys, os, time
import subprocess as sp

def main(argv):

	if argv == 1:
		print "Usage: ./autopy.py [input_file]"

	if argv > 1:
		sp.call(['srcml', argv[1], '-o', 'class_file_test.hpp.xml'])# '--register-ext', 'h=C++',
		print "[=	Finished srcml..."
		sp.call(['srcyuml', 'class_file_test.hpp.xml', 'class_file_test.hpp.yuml'])
		print "[=	Finished srcyuml..."
		sp.call(['srcYUML2graphViz.py', 'class_file_test.hpp.yuml', 'class_file_test.outxt'])
		print "[=	Finished conversion..."
		sp.call(['dot', '-Tpdf', 'class_file_test.outxt', '-o', 'pic.pdf'])#'-Gdpi=900'
		print "[=	Finished picture..."
		#sp.call(['rm', 'class_file_test.hpp.xml', 'class_file_test.hpp.yuml', 'class_file_test.outxt'])
		print "[=	Removed extra files..."
		print "[=	Completed!"
		#sp.call(['eog', 'pic.jpg'])
		#sp.call(['eog', 'pic.png'])
		sp.call(['evince', 'pic.pdf'])

if __name__ == '__main__':
	main(sys.argv)
